//! Linux system-DNS enforcement (PRD `leak-protection.md`, FR3): point the OS
//! resolver at the tunnel's DNS servers while connected, restore on disconnect.
//!
//! Two mechanisms, tried in order:
//!
//! 1. **systemd-resolved** (`resolvectl`): set the servers on the tunnel
//!    *link* plus the `~.` routing domain, which makes the tunnel resolver win
//!    for every name. This is the clean path — the settings are per-link, so
//!    they vanish with the interface even after a crash, and
//!    `resolvectl revert <iface>` undoes them explicitly.
//! 2. **`/etc/resolv.conf` swap** (non-resolved distros): *rename* the current
//!    file to a backup (rename preserves a symlinked setup exactly) and write
//!    our own. Restore renames the backup over our file. If a backup already
//!    exists on engage, it is kept — it's the pre-Ferrum original from a
//!    crashed session, and overwriting it would lose the user's real config.
//!
//! Shared by the CLI, the desktop's direct-fallback path, and the
//! privileged-helper daemon (mirrors [`crate::firewall`] / [`crate::leakguard`]).

use std::io;
use std::net::IpAddr;
use std::path::Path;
use std::process::Command;

/// The resolv.conf path this module manages.
pub const RESOLV_CONF: &str = "/etc/resolv.conf";
/// Where the pre-Ferrum resolv.conf is parked while ours is active.
pub const RESOLV_CONF_BACKUP: &str = "/etc/resolv.conf.ferrum-backup";

/// `resolvectl dns <iface> <server>…` — set the link's DNS servers.
pub fn resolvectl_dns_args(iface: &str, servers: &[IpAddr]) -> Vec<String> {
    let mut args = vec!["dns".to_string(), iface.to_string()];
    args.extend(servers.iter().map(|s| s.to_string()));
    args
}

/// `resolvectl domain <iface> ~.` — the routing-domain trick: `~.` makes this
/// link the preferred resolver for *all* names, not just its own suffixes.
pub fn resolvectl_domain_args(iface: &str) -> [String; 3] {
    ["domain".to_string(), iface.to_string(), "~.".to_string()]
}

/// `resolvectl revert <iface>` — drop every per-link setting we made.
pub fn resolvectl_revert_args(iface: &str) -> [String; 2] {
    ["revert".to_string(), iface.to_string()]
}

/// The resolv.conf contents pointing at `servers` (fallback path).
pub fn resolv_conf_contents(servers: &[IpAddr]) -> String {
    let mut out =
        String::from("# Generated by Ferrum (leak protection) — restored on disconnect.\n");
    for s in servers {
        out.push_str(&format!("nameserver {s}\n"));
    }
    out
}

/// Run `resolvectl` with `args`; `Ok` only on a zero exit.
fn run_resolvectl<S: AsRef<std::ffi::OsStr>>(args: &[S]) -> io::Result<()> {
    let out = Command::new("resolvectl").args(args).output()?;
    if out.status.success() {
        Ok(())
    } else {
        Err(io::Error::other(format!(
            "resolvectl exited with {}: {}",
            out.status,
            String::from_utf8_lossy(&out.stderr).trim()
        )))
    }
}

/// Swap `conf` for our generated file, parking the original at `backup`.
/// Path-parameterized so the dance is testable without touching `/etc`.
fn swap_resolv_conf(conf: &Path, backup: &Path, contents: &str) -> io::Result<()> {
    // A pre-existing backup is the original from a crashed session — keep it,
    // so restore always lands the user's real config.
    if !backup.exists() {
        std::fs::rename(conf, backup)?;
    }
    std::fs::write(conf, contents)
}

/// Undo [`swap_resolv_conf`]: move the backup over our file, if one exists.
fn restore_resolv_conf(conf: &Path, backup: &Path) -> io::Result<()> {
    if backup.exists() {
        std::fs::rename(backup, conf)?;
    }
    Ok(())
}

/// Point system DNS at `servers` for the life of the connection: per-link via
/// systemd-resolved when available, else the `/etc/resolv.conf` swap.
pub fn set_dns(iface: &str, servers: &[IpAddr]) -> io::Result<()> {
    if servers.is_empty() {
        return Err(io::Error::other("no DNS servers to set"));
    }
    match run_resolvectl(&resolvectl_dns_args(iface, servers))
        .and_then(|()| run_resolvectl(&resolvectl_domain_args(iface)))
    {
        Ok(()) => Ok(()),
        // No resolvectl / no resolved / link not managed — fall back to the file.
        Err(_) => swap_resolv_conf(
            Path::new(RESOLV_CONF),
            Path::new(RESOLV_CONF_BACKUP),
            &resolv_conf_contents(servers),
        ),
    }
}

/// Restore pre-connection DNS. Best-effort on both mechanisms (each is a no-op
/// where it wasn't the one used), so it's safe to call unconditionally on
/// disconnect — including cleaning up after a crashed previous session.
pub fn restore_dns(iface: &str) -> io::Result<()> {
    // The revert fails harmlessly when resolvectl/the link isn't there.
    let _ = run_resolvectl(&resolvectl_revert_args(iface));
    restore_resolv_conf(Path::new(RESOLV_CONF), Path::new(RESOLV_CONF_BACKUP))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn servers() -> Vec<IpAddr> {
        vec!["10.99.0.53".parse().unwrap(), "fd00::53".parse().unwrap()]
    }

    #[test]
    fn resolvectl_args_set_link_dns_and_route_all_names() {
        assert_eq!(
            resolvectl_dns_args("ferrum0", &servers()),
            vec!["dns", "ferrum0", "10.99.0.53", "fd00::53"]
        );
        assert_eq!(
            resolvectl_domain_args("ferrum0"),
            ["domain", "ferrum0", "~."]
        );
        assert_eq!(resolvectl_revert_args("ferrum0"), ["revert", "ferrum0"]);
    }

    #[test]
    fn resolv_conf_lists_every_server() {
        let c = resolv_conf_contents(&servers());
        assert!(c.contains("nameserver 10.99.0.53\n"));
        assert!(c.contains("nameserver fd00::53\n"));
        assert!(
            c.starts_with('#'),
            "labeled so an operator knows its origin"
        );
    }

    /// The full swap/restore dance in a temp dir — including the crash case
    /// (engage twice, restore once) landing the *original* contents back.
    #[test]
    fn swap_and_restore_round_trip_preserves_the_original() {
        let dir = std::env::temp_dir().join(format!("ferrum-dns-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let conf = dir.join("resolv.conf");
        let backup = dir.join("resolv.conf.backup");
        std::fs::write(&conf, "nameserver 192.0.2.1\n").unwrap();

        swap_resolv_conf(&conf, &backup, "nameserver 10.99.0.53\n").unwrap();
        assert_eq!(
            std::fs::read_to_string(&conf).unwrap(),
            "nameserver 10.99.0.53\n"
        );
        assert_eq!(
            std::fs::read_to_string(&backup).unwrap(),
            "nameserver 192.0.2.1\n"
        );

        // A second engage (e.g. after a crash) must keep the original backup.
        swap_resolv_conf(&conf, &backup, "nameserver 10.99.0.54\n").unwrap();
        assert_eq!(
            std::fs::read_to_string(&backup).unwrap(),
            "nameserver 192.0.2.1\n"
        );

        restore_resolv_conf(&conf, &backup).unwrap();
        assert_eq!(
            std::fs::read_to_string(&conf).unwrap(),
            "nameserver 192.0.2.1\n"
        );
        assert!(!backup.exists());

        // Restoring again with no backup is a clean no-op.
        restore_resolv_conf(&conf, &backup).unwrap();

        let _ = std::fs::remove_dir_all(&dir);
    }
}
